parameters:
    env(DATABASE_URL): '' # fallback DATABASE_URL (for running cache:warmup even)

doctrine:
    dbal:
        default_connection: from_env
        connections:
            from_env:
                driver: 'pdo_mysql'
                server_version: '5.7'
                charset: utf8
                default_table_options:
                    charset: utf8
                    collate: utf8_unicode_ci
                dbname:    '%env(DATABASE_SCHEMA)%'
                host:      '%env(DATABASE_HOST)%'
                password:  '%env(DATABASE_PASSWORD)%'
                port:      '%env(DATABASE_PORT)%'
                user:      '%env(DATABASE_USER)%'
                #url: '%env(resolve:DATABASE_URL)%'
            from_env_postgres:
                mapping_types:
                        work_hours_requisite_period: string
                        work_hours_planned_period: string
                        clocking_action: string
                driver_class: App\PostgresDriver
                server_version: '10.1.1'
                charset: utf8
                dbname:    '%env(DATABASE_SCHEMA)%'
                host:      '%env(DATABASE_HOST)%'
                password:  '%env(DATABASE_PASSWORD)%'
                port:      '%env(DATABASE_PORT)%'
                user:      '%env(DATABASE_USER)%'

    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: annotation
                dir: '%kernel.project_dir%/src/Entity'
                prefix: 'App\Entity'
                alias: App
