framework:
    #session:
    #    handler_id: ~
    
    secret: '%env(APP_SECRET)%'
    csrf_protection: false
    #http_method_override: true

    php_errors:
        log: true
    cache:
        prefix_seed: jaroslav/billie-assignment
    ide: phpstorm
