parameters:
    env(DATABASE_URL): '' # fallback
    memcached_localhost:
        type: memcached
        host: localhost
        port: 11211
        instance_class: Memcached
    def_con: 'from_env'


doctrine:
    orm:
        auto_generate_proxy_classes: true
        query_cache_driver: '%memcached_localhost%'
        metadata_cache_driver: '%memcached_localhost%'
        result_cache_driver: '%memcached_localhost%'

        #connections:
        #default_entity_manager: original
        #entity_managers:
        #    original:
        #        query_cache_driver: '%memcached_localhost%'
        #        metadata_cache_driver: '%memcached_localhost%'
        #        result_cache_driver: '%memcached_localhost%'
        #        connection: '%def_con%'
        #        naming_strategy: doctrine.orm.naming_strategy.underscore
        #        auto_mapping: false
        #        mappings:
        #            TimeTracking:
        #                is_bundle: false
        #                type: annotation
        #                dir: '%kernel.project_dir%/src/php/TimeTracking/Model'
        #                prefix: TimeTracking\Model
        #                alias: TimeTracking
        #                mapping: true
    #orm:
    #    auto_generate_proxy_classes: false
    #    metadata_cache_driver:
    #        type: service
    #        id: doctrine.system_cache_provider
    #    query_cache_driver:
    #        type: service
    #        id: doctrine.system_cache_provider
    #    result_cache_driver:
    #        type: service
    #        id: doctrine.result_cache_provider

services:
    doctrine.result_cache_provider:
        class: Symfony\Component\Cache\DoctrineProvider
        public: false
        arguments:
            - '@doctrine.result_cache_pool'
    doctrine.system_cache_provider:
        class: Symfony\Component\Cache\DoctrineProvider
        public: false
        arguments:
            - '@doctrine.system_cache_pool'

framework:
    cache:
        pools:
            doctrine.result_cache_pool:
                adapter: cache.app
            doctrine.system_cache_pool:
                adapter: cache.system


# refs:
#
# https://symfony.com/doc/current/reference/configuration/doctrine.html
# https://stackoverflow.com/questions/9361976/can-be-entities-stored-in-other-location-than-in-entity-directory
