parameters:
    locale: 'en'
    #exterlal_service_base_url: "https://what.ever/hello-world"

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.
        public: false

    controllers: { namespace: App\Controller\, resource: '../src/Controller/*' }
    services: { namespace: App\Service\, resource: '../src/Service/*' }
    commands: { namespace: App\Command\, resource: '../src/Command/*' }
    exception_responses:
        namespace: App\Http\Responses\
        resource: '../src/Http/Responses/*'
        tags:
        - { name: kernel.event_listener, event: kernel.exception }


    twig.exception_listener:
        class: stdClass # disable fancy exceptions in the browser

    simple_logger:
        class: App\ExceptionLogger # log to sink configured in php.ini
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

